name: CCC Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests

      - name: Run CCC Monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FIRMS_MAP_KEY: ${{ secrets.FIRMS_MAP_KEY }}
          DEBUG_FIRMS: "1"
        run: |
          python main.py
